name: Deploy Frontend to AWS S3 & CloudFront

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # Relies on OIDC authentication tokens
  contents: read    # Grants access to check out repository code

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Authenticate with AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::940127592255:role/github-actions-deploy-role
          aws-region: eu-central-1

      - name: Sync Frontend Code to S3 Bucket
        run: |
          aws s3 cp index.html s3://muhammad-resume-2026-fra/index.html

      - name: Invalidate Global CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id EQHI453NYWSSZ --paths "/*"
